/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eta_servicetest;

import org.apache.http.HttpStatus;
import org.junit.BeforeClass;
import org.junit.Test;

import static io.restassured.RestAssured.*;
import static org.hamcrest.Matchers.*;

public class Exercicio01 {

    @BeforeClass
    public static void preCondition(){
        baseURI = "http://localhost";
        port = 3000;
    }

    @Test
    public void getUsuarios() {
        when()
                .get("/usuarios")
        .then()
                .statusCode(HttpStatus.SC_OK);
    }

    @Test
    public void postUsuarios() {
        String userID = given()
                .body("{\n" +
                        "  \"nome\": \"Thiago Cesar Andrade\",\n" +
                        "  \"email\": \"tcandrade@mailinator.com\",\n" +
                        "  \"password\": \"teste@123\",\n" +
                        "  \"administrador\": \"true\"\n" +
                        "}")
                .contentType("application/json")
        .when()
                .post("/usuarios")
        .then()
                .statusCode(HttpStatus.SC_CREATED)
                .body("message", is("Cadastro realizado com sucesso"))
                .extract().path("_id");
    }
}
